DROP TABLE users;
DROP TABLE document;
DROP TABLE deadline;
DROP TABLE role;
DROP TABLE feedback;
DROP TABLE user_roles;
DROP TABLE user_supervisors;
DROP TABLE user_coordinators;
DROP TABLE submission;